version: "3.8"

services:
  app:
    build: .
    ports:
      - 5000:5000
    environment:
      - DATABASE_URL=postgresql://postgres:${POSTGRES_PASSWORD}@db:5432/db_name
    depends_on:
      db:
        condition: service_healthy
  db:
    image: postgres
    restart: always
    environment:
      - POSTGRES_DB=db_name
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=${POSTGRES_PASSWORD}
    volumes:
      - postgres-data:/var/lib/postgresql/data
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U postgres"]
      interval: 5s
      timeout: 5s
      retries: 10

volumes:
  postgres-data: