"""empty message

Revision ID: 739420fcab4f
Revises: cc23716fe11e
Create Date: 2024-02-26 11:47:40.871492

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '739420fcab4f'
down_revision = 'cc23716fe11e'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('choice', schema=None) as batch_op:
        batch_op.add_column(sa.Column('correct', sa.Boolean(), nullable=False))
        batch_op.drop_column('is_correct')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('choice', schema=None) as batch_op:
        batch_op.add_column(sa.Column('is_correct', sa.BOOLEAN(), nullable=False))
        batch_op.drop_column('correct')

    # ### end Alembic commands ###
